### ISSUE TITLE
Stucked in garage after restarting

### ISSUE THREAD

**Issue by WnDSolutions** [TinusNL/esx_garaging#1]
Hello,

1. After restarting I am stucked in the garage without blips to get out of it. Is there any way to fix this?

2.  I am getting this error while using the laptop and it doesn't show anything
![image](https://user-images.githubusercontent.com/6540983/109605812-6b123700-7b2e-11eb-89b8-3e918ef9bee1.png)

3. Is it possible to make it so we can sell the garages?

4. Is there some kind of spawn protection? Like if there is a car outside another player can't get out till the car leaves? If not it will be cool. :P

Thanks!
And good job!

**Comment by WnDSolutions** [comment]
Hello again, getting the following errors with the new update when trying to enter garage

![image](https://user-images.githubusercontent.com/6540983/110390561-db5d1300-806e-11eb-846a-ecaae98fa397.png)

**Comment by TinusNL** [comment]
When are you getting this error?

**Comment by WnDSolutions** [comment]
> When are you getting this error?

When trying to enter the garage

**Comment by TinusNL** [comment]
I think i might have fixed the issue. Just re download the complete resource because there are edits to each file.

**Comment by WnDSolutions** [comment]
Hello, it's working now.

1. What about the disconnect in the garage? When players disconnect in there they can't get out. Is there a way to make them spawn outside of the garage?
2. I tried to rename the first garage to `Free garage` and it gives me the error I was getting before, do I have to change the name somewhere else too maybe?
3. Is it possible to add an option to invite/kick a player in the garage like with esx_properties?
4. Is it possible to make it so the default garage doesn't give money to players when they sell it since they get it for free?
5. I noticed that if you walk away from the laptop with the menu open it stucks there till you choose something and press backspace, can you make it so that the menu close when you walk away from the laptop? (Edit: If you open the menu and you don't choose something you can't close it)

I'm sorry, many things I know.. :P
Thanks a lot!

**Comment by TinusNL** [comment]
I already fixed number 4 and wil be looking into 5!

**Comment by WnDSolutions** [comment]
> I already fixed number 4 and wil be looking into 5!

You are the best, let's make it the best garage system, I'm tired of all the bugged ones out there.
