### ISSUE TITLE
stuck in garage after restart

### ISSUE THREAD

**Issue by vcmanny** [TinusNL/esx_garaging#3]
hey when i restart my server i get stuck in the garage, any way to make it that you spawn outside?

**Comment by TinusNL** [comment]
Hey

I currently am working/thinking of a solution to this since you obviously can't run code once the server is offline. In the new release, I did fix the problem that made you get stuck when leaving!

**Comment by vcmanny** [comment]
@TinusNL I installed the latest version & got stuck after a restart. Also Is there a way I can configure it that only one person can buy each garage?

**Comment by TinusNL** [comment]
That is litterally what i said...

> I currently am working/thinking of a solution to this since you obviously can't run code once the server is offline.

**Comment by vcmanny** [comment]
@TinusNL you also said "In the new release, I did fix the problem that made you get stuck when leaving!" got confused, my bad.

**Comment by vcmanny** [comment]
@TinusNL can I make it that once a garage is bought no one else can buy it?

**Comment by vcmanny** [comment]
@TinusNL ???
